version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - contextcheck
    - errorlint
    - gosec
    - noctx
    - revive

formatters:
  enable:
    - gofmt
