/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    doctors: Doctor;
    'doctor-reviews': DoctorReview;
    'appointment-slots': AppointmentSlot;
    appointments: Appointment;
    'knowledge-files': KnowledgeFile;
    'knowledge-documents': KnowledgeDocument;
    'unresolved-queries': UnresolvedQuery;
    'chat-suggested-questions': ChatSuggestedQuestion;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    'doctor-reviews': DoctorReviewsSelect<false> | DoctorReviewsSelect<true>;
    'appointment-slots': AppointmentSlotsSelect<false> | AppointmentSlotsSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    'knowledge-files': KnowledgeFilesSelect<false> | KnowledgeFilesSelect<true>;
    'knowledge-documents': KnowledgeDocumentsSelect<false> | KnowledgeDocumentsSelect<true>;
    'unresolved-queries': UnresolvedQueriesSelect<false> | UnresolvedQueriesSelect<true>;
    'chat-suggested-questions': ChatSuggestedQuestionsSelect<false> | ChatSuggestedQuestionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'rag-settings': RagSetting;
  };
  globalsSelect: {
    'rag-settings': RagSettingsSelect<false> | RagSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role?: ('admin' | 'patient') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describes the image for screen readers.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: string;
  name: string;
  specialization: string;
  qualifications?: string | null;
  /**
   * Years of clinical experience shown on the doctor profile. Set or update this when editing the doctor.
   */
  experienceYears?: number | null;
  photo?: (string | null) | Media;
  bio?: string | null;
  /**
   * Clinic address shown to patients. Auto-filled when you pick a map pin.
   */
  address?: string | null;
  /**
   * Set by clicking the map above (or enter manually).
   */
  latitude?: number | null;
  /**
   * Set by clicking the map above (or enter manually).
   */
  longitude?: number | null;
  /**
   * Cached average from patient reviews (1–5). Updated automatically.
   */
  ratingAverage?: number | null;
  /**
   * Number of patient reviews. Updated automatically.
   */
  reviewCount?: number | null;
  /**
   * Inactive doctors are hidden from the mobile application.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Patient ratings and comments for doctors after a visit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctor-reviews".
 */
export interface DoctorReview {
  id: string;
  patient: string | User;
  /**
   * Display name captured at submit time so reviews stay readable publicly.
   */
  patientName: string;
  doctor: string | Doctor;
  /**
   * The past visit this review is tied to, when available.
   */
  appointment?: (string | null) | Appointment;
  /**
   * 1 (poor) to 5 (excellent).
   */
  rating: number;
  /**
   * Optional written feedback from the patient.
   */
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: string;
  patient: string | User;
  doctor: string | Doctor;
  slot: string | AppointmentSlot;
  status: 'booked' | 'cancelled';
  bookedAt: string;
  cancelledAt?: string | null;
  /**
   * Name the clinic should use when contacting the patient about this visit.
   */
  contactName: string;
  /**
   * Phone number for appointment reminders or clinic callbacks.
   */
  contactPhone: string;
  /**
   * Email the clinic can use for this appointment.
   */
  contactEmail: string;
  /**
   * Special request / comment from the patient. Patients set this when booking or from appointment details.
   */
  patientNote?: string | null;
  /**
   * Visible to the patient on their appointment details. Use for prep instructions, reminders, or notes from the clinic.
   */
  doctorComment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Create a one-time slot, or a daily/weekday series that expands through the repeat-until date. Overlapping times for the same doctor are rejected.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointment-slots".
 */
export interface AppointmentSlot {
  id: string;
  doctor: string | Doctor;
  /**
   * First occurrence for recurring slots; every generated day keeps this clock time.
   */
  startsAt: string;
  /**
   * Computed from start time + duration. Used for overlap checks.
   */
  endsAt: string;
  durationMinutes: number;
  status: 'available' | 'booked';
  /**
   * Recurring choices create matching slots through the repeat-until date.
   */
  scheduleType: 'once' | 'daily' | 'weekdays';
  /**
   * Inclusive end date for the series (required for daily/weekday schedules).
   */
  repeatUntil?: string | null;
  /**
   * Shared id for slots generated from one recurring create.
   */
  seriesId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Upload a PDF here to index it for the healthcare assistant. A Knowledge Document is created automatically and embedded asynchronously.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-files".
 */
export interface KnowledgeFile {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Indexed PDFs for the healthcare assistant. Uploading under Knowledge Files also creates a document here automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-documents".
 */
export interface KnowledgeDocument {
  id: string;
  title: string;
  /**
   * The source PDF. Replacing it should also bump the version.
   */
  file: string | KnowledgeFile;
  version: number;
  /**
   * Maintained by the RAG ingestion pipeline.
   */
  indexStatus: 'pending' | 'processing' | 'indexed' | 'failed';
  indexedAt?: string | null;
  indexError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unresolved-queries".
 */
export interface UnresolvedQuery {
  id: string;
  question: string;
  questionKey?: string | null;
  user: string | User;
  sessionId?: string | null;
  status: 'new' | 'resolved';
  humanResponse?: string | null;
  /**
   * Why the sufficiency gates declined to answer.
   */
  retrievalReason?: ('no_results' | 'below_threshold' | 'low_coverage' | 'llm_declined') | null;
  /**
   * Highest vector-search score for this question.
   */
  topScore?: number | null;
  resolvedAt?: string | null;
  /**
   * When the clinic reply was saved for the patient to read.
   */
  deliveredAt?: string | null;
  reviewedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Shown as quick-start chips in the healthcare assistant chat.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-suggested-questions".
 */
export interface ChatSuggestedQuestion {
  id: string;
  /**
   * Exact text sent to the chatbot when the chip is tapped.
   */
  question: string;
  /**
   * Lower numbers appear first.
   */
  order: number;
  /**
   * Inactive questions are hidden from the mobile app.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'doctors';
        value: string | Doctor;
      } | null)
    | ({
        relationTo: 'doctor-reviews';
        value: string | DoctorReview;
      } | null)
    | ({
        relationTo: 'appointment-slots';
        value: string | AppointmentSlot;
      } | null)
    | ({
        relationTo: 'appointments';
        value: string | Appointment;
      } | null)
    | ({
        relationTo: 'knowledge-files';
        value: string | KnowledgeFile;
      } | null)
    | ({
        relationTo: 'knowledge-documents';
        value: string | KnowledgeDocument;
      } | null)
    | ({
        relationTo: 'unresolved-queries';
        value: string | UnresolvedQuery;
      } | null)
    | ({
        relationTo: 'chat-suggested-questions';
        value: string | ChatSuggestedQuestion;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  name?: T;
  specialization?: T;
  qualifications?: T;
  experienceYears?: T;
  photo?: T;
  bio?: T;
  address?: T;
  latitude?: T;
  longitude?: T;
  ratingAverage?: T;
  reviewCount?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctor-reviews_select".
 */
export interface DoctorReviewsSelect<T extends boolean = true> {
  patient?: T;
  patientName?: T;
  doctor?: T;
  appointment?: T;
  rating?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointment-slots_select".
 */
export interface AppointmentSlotsSelect<T extends boolean = true> {
  doctor?: T;
  startsAt?: T;
  endsAt?: T;
  durationMinutes?: T;
  status?: T;
  scheduleType?: T;
  repeatUntil?: T;
  seriesId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  patient?: T;
  doctor?: T;
  slot?: T;
  status?: T;
  bookedAt?: T;
  cancelledAt?: T;
  contactName?: T;
  contactPhone?: T;
  contactEmail?: T;
  patientNote?: T;
  doctorComment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-files_select".
 */
export interface KnowledgeFilesSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-documents_select".
 */
export interface KnowledgeDocumentsSelect<T extends boolean = true> {
  title?: T;
  file?: T;
  version?: T;
  indexStatus?: T;
  indexedAt?: T;
  indexError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unresolved-queries_select".
 */
export interface UnresolvedQueriesSelect<T extends boolean = true> {
  question?: T;
  questionKey?: T;
  user?: T;
  sessionId?: T;
  status?: T;
  humanResponse?: T;
  retrievalReason?: T;
  topScore?: T;
  resolvedAt?: T;
  deliveredAt?: T;
  reviewedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-suggested-questions_select".
 */
export interface ChatSuggestedQuestionsSelect<T extends boolean = true> {
  question?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Choose the chat and embedding providers the knowledge assistant uses. Keys stay in Payload. The Go service only calls this CMS. Answers come from documents uploaded under Knowledge Files / Knowledge Documents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rag-settings".
 */
export interface RagSetting {
  id: string;
  chatProvider: 'ollama' | 'openai' | 'anthropic' | 'google' | 'openrouter' | 'deepseek';
  /**
   * One example per provider — Ollama: llama3.2 · OpenAI: gpt-4o-mini · Anthropic: claude-sonnet-4-5 · Google: gemini-2.0-flash · OpenRouter: openai/gpt-4o-mini · DeepSeek: deepseek-flash. Switching provider fills the example; you can still type any model id (deepseek-v4-pro).
   */
  chatModel: string;
  /**
   * Leave blank for the provider default. DeepSeek: https://api.deepseek.com. OpenRouter: https://openrouter.ai/api/v1. Google: https://generativelanguage.googleapis.com/v1beta. Compose Ollama: http://ollama:11434/v1. Host Ollama: http://127.0.0.1:11434/v1.
   */
  chatBaseUrl?: string | null;
  /**
   * Stored only in Payload. Never sent to the mobile app or committed to git.
   */
  chatApiKey?: string | null;
  /**
   * Anthropic and DeepSeek have no embeddings API. Chat can still be DeepSeek or Claude while embeddings stay on Ollama, OpenAI, Google, or OpenRouter.
   */
  embedProvider: 'ollama' | 'openai' | 'google' | 'openrouter';
  /**
   * One example per provider — Ollama: nomic-embed-text (768) · OpenAI: text-embedding-3-small (1536) · Google: gemini-embedding-001 (768) · OpenRouter: openai/text-embedding-3-small (1536). Anthropic and DeepSeek have no embeddings API. Switching provider fills the example. Re-ingest after changing model or dimensions.
   */
  embedModel: string;
  /**
   * Leave blank for the provider default. Same Ollama URL rules as chat.
   */
  embedBaseUrl?: string | null;
  /**
   * Stored only in Payload.
   */
  embedApiKey?: string | null;
  /**
   * Must match the model output and the Atlas vector index. Changing this requires dropping the index and re-ingesting every document.
   */
  embedDimensions: number;
  /**
   * Atlas cosine is (1+cos)/2, so ~0.50 is unrelated. Drop chunks below this floor.
   */
  minScore: number;
  /**
   * A hit at or above this is a strong vector match. Seeded document questions typically land here after nomic prefixes.
   */
  strongScore: number;
  /**
   * Minimum chunks above the score floor before the LLM is asked.
   */
  minChunks: number;
  /**
   * Fraction of question content-words that must appear in retrieved text. High similarity + low coverage is "related topic, wrong question".
   */
  minCoverage: number;
  maxConcurrency: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rag-settings_select".
 */
export interface RagSettingsSelect<T extends boolean = true> {
  chatProvider?: T;
  chatModel?: T;
  chatBaseUrl?: T;
  chatApiKey?: T;
  embedProvider?: T;
  embedModel?: T;
  embedBaseUrl?: T;
  embedApiKey?: T;
  embedDimensions?: T;
  minScore?: T;
  strongScore?: T;
  minChunks?: T;
  minCoverage?: T;
  maxConcurrency?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}